spring.application.name=ms-secucloud
server.port=8080

spring.datasource.url=jdbc:h2:mem:secuclouddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=never

server.error.include-message=always
server.error.include-stacktrace=never

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/a92eda2f-7921-4085-914d-dae2ca6b6aba/v2.0
logging.level.org.springframework.security=DEBUG
