spring.application.name=ms-secucloud
server.port=8080

spring.datasource.url=jdbc:h2:mem:secuclouddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=never

server.error.include-message=always
server.error.include-stacktrace=never

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cloudnative1gabrielgrobier.b2clogin.com/cloudnative1gabrielgrobier.onmicrosoft.com/B2C_1_prueba-t2/oauth2/v2.0/authorize
logging.level.org.springframework.security=DEBUG
